# Generated by Django 4.2.3 on 2023-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_fabrica_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
