# Generated by Django 4.2.3 on 2023-08-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrica',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
